[book]
title = "Recipes"
authors = ["troyerta"]
description = "An online recipe book"
language = "en"

[build]
create-missing = false

# Convert all chapter files named README.md into index.md. That is to say, all README.md would be rendered to an index file index.html in the rendered book.
# [preprocessor.index]

# [preprocessor.summary_gen]
# command = "python3 summary_gen.py"

[output.html]
additional-js = ["js/enable-checkboxes.js"]
no-section-label = true
google-analytics = "UA-164779968-1"

[output.html.fold]
enable = true

# [output.linkcheck]
# follow-web-links = false
# traverse-parent-directories = false

# The User-Agent to use when sending web requests
# user-agent = "mdbook-linkcheck-0.4.0"

# The number of seconds a cached result is valid for (12 hrs by default)
# cache-timeout = 43200

# How should warnings be treated?
#
# - "warn" will emit warning messages
# - "error" treats all warnings as errors, failing the linkcheck
# - "ignore" will ignore warnings, suppressing diagnostic messages and allowing
#   the linkcheck to continuing
# warning-policy = "error"

# Extra HTTP headers that must be send to certain web sites
# in order to link check to succeed
#
# This is a dictionary (map), with keys being regexes
# matching a set of web sites, and values being an array of
# the headers.
# [http-headers]
# Any hyperlink that contains this regexp will be sent
# the "Accept: text/html" header
# "crates\.io" = ["Accept: text/html"]

# mdbook-linkcheck will interpolate environment variables
# into your header via $IDENT.
#
# If this is not what you want
# you must escape the `$` symbol, like `\$TOKEN`. `\` itself can also be escaped
# via `\\`.
# "website\.com" = ["Authorization: Basic $TOKEN"]
